### ISSUE TITLE
`eis-show-fonts` need a way to "show mono font only"

### ISSUE THREAD

**Issue by shenlebantongying** [bkaestner/eis.el#1]
`eis-show-fonts` is pretty nice, finally i can have a font-tester inside emacs.

However, a lot of fonts in system are useless and most emacs users need mono fonts. Some way to filter them out is needed.

There must be a solution to do so, because i have saw "show mono font only" in a lot of softwares.
https://emacs.stackexchange.com/questions/50212/is-there-a-better-way-in-emacs-lisp-to-print-the-list-of-monospace-fonts-in-a-se
 
<img width="400" alt="Screen Shot 2022-03-16 at 3 03 07 AM" src="https://user-images.githubusercontent.com/20123683/158534672-15d24700-6224-4c15-8d57-34aef0693fa0.png">

(If possible, i actually want to switch to the font when i click the font name)

**Comment by bkaestner** [comment]
Hey there, I've added a new customization option, see `eis-font-filter`. It works on my system (Emacs 27.2 on Windows 10), but I'd be interested in additional feedback.

For your use case, try
```lisp
(setq eis-font-filter 'monospace)
(eis-show-fonts)
```
Please reopen the issue if the solution does not work!

> (If possible, i actually want to switch to the font when i click the font name)

As your *default font*? Hm, that might be worth another issue.
